### ISSUE TITLE
Text color in dropdown "wrong"

### ISSUE THREAD

**Issue by chrisonline** [SimplicityApks/ReminderDatePicker#33]
I am currently in BETA test with a few users.
One has reported that the text inside the dropdown spinner are "black on black" instead of grey or white.

See this screenshot:
https://lh4.googleusercontent.com/-eZbmx2_cQfw/Vjn2paEJaLI/AAAAAAAAA3U/vp1OLi4UmjM/w537-h557-no/Screenshot_2015-11-03-08-46-20.png

On my Nexus 4/ Nexus 5 or Galaxy S6 Edge it is correct.
The same color as the time on the right.

**Comment by SimplicityApks** [comment]
Mmmhh this doesn't look quite allright :P. I assume you are using the newest sources and support lib, including commit a52b837c? Can you tell me what this user is running? Looks like modified KitKat to me (CM11 or earlier). The problem is that I can't really be sure what different manufacturers and mods did to "?android:textColorSecondary", which is used by the dropdown item in this case.

I'll do some more tests when I find the time, but it's like finding the needle in the haystack. I also don't see a way to move around using the default resources here.

But great you're in beta ;) looking forward to the material update!

**Comment by chrisonline** [comment]
I use the last support lib and official ReminderDatePicker version via Gradle compile --> Version 1.2.1 !
So if a52b837 is not in 1.2.1 I don't use it.

I have just asked the user for android verison/phone model/rom version.
Once I get the info I will update you.

**Comment by chrisonline** [comment]
got the info from the user:
THL5000, Custom ROM 4.4. - Lite 2.1﻿

So it is a "Lite Rom" and Android 4.4.
Seems you're right that the "Lite Rom" has changed the textColorSecondary.

**Comment by SimplicityApks** [comment]
Well it is (most probably) already fixed in the latest commit, because it was inverted on Honeycomb through KitKat and I changed that in the commit. That reminds me that I have to upload it to maven, will do that soon I hope.

**Comment by chrisonline** [comment]
OK, let me know if you made a new verison and I will use that version.

**Comment by chrisonline** [comment]
Just added it to the latest beta. I will let you know if it is fixed.
Thanks!

**Comment by chrisonline** [comment]
User reported back. It is now fixed!!! Great, thanks!
