### ISSUE TITLE
how can i change the spinner_item margin?

### ISSUE THREAD

**Issue by Frankenstein666** [SimplicityApks/ReminderDatePicker#35]

**Comment by Frankenstein666** [comment]
also how can i change spinner dropdown item colors?

**Comment by SimplicityApks** [comment]
Changing the spinner items' appearance is not directly supported by the api since you could break a lot with that. However you can easily override the [R.layout.twin_text_item](https://github.com/SimplicityApks/ReminderDatePicker/blob/master/lib/src/main/res/layout/twin_text_item.xml) and the [R.layout.twin_text_dropdown_item](https://github.com/SimplicityApks/ReminderDatePicker/blob/master/lib/src/main/res/layout/twin_text_dropdown_item.xml) by placing your own version of the files in your layout resource folder. For the color, it should be possible to customize it using the textColorSecondaryInverse in your styles.

Sorry it took me so long to answer, I'm currently on vacation.

**Comment by Frankenstein666** [comment]
Thabk you, One more thing, is there a way to override the timepicker and datepicker colors, by default it is sky blue, i need to change the colors to match my app theme.

**Comment by chrisonline** [comment]
You can override the date/timepicker color with the color attribute "datepicker_primary"!

**Comment by SimplicityApks** [comment]
closing as this is answered (and outdated) :P
